name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        run: |
          echo "${{ secrets.AWS_ECR_PASSWORD }}" | docker login --username AWS --password-stdin 008971655298.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          docker build -t fastapi-app .
          docker push 008971655298.dkr.ecr.ap-south-1.amazonaws.com/fastapi-app:latest

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name my-eks-cluster --region ap-south-1
          helm upgrade --install fastapi-release ./fastapi-chart
