name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Configure AWS Credentials for authentication
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 008971655298.dkr.ecr.ap-south-1.amazonaws.com

      # Build and Push Docker Image to ECR
      - name: Build and Push Docker Image
        run: |
          cd fastapi-app
          docker build -t fastapi-app .
          docker tag fastapi-app:latest 008971655298.dkr.ecr.ap-south-1.amazonaws.com/fastapi-app:latest
          docker push 008971655298.dkr.ecr.ap-south-1.amazonaws.com/fastapi-app:latest

      # Deploy to EKS using Helm
      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name assignment-eks-cluster --region ap-south-1
          helm upgrade --install fastapi-release ./fastapi-chart
          kubectl get svc
